defconfig: Add moto defconfigs
Add defconfigs for jordan/dubai, lahaina chipset, debug
builds and the factory.

Change-Id: I38d8b5f297cab35c7497f14cfbed6d440770a740
Signed-off-by: xiaoy3 <xiaoy3@motorola.com>
Reviewed-on: https://gerrit.mot.com/1684118
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Tested-by: Jira Key
Submit-Approved: Jira Key

dubai:touch: Fix duplicated symbol and crash issue

[   35.553642] synaptics_i2c: exports duplicate symbol syna_tcm_bus_exit (owned by kernel)
[   35.562187] init: Command 'insmod /vendor/lib/modules/synaptics_i2c.ko' action=early-init (/vendor/etc/init/hw/init.mmi.overlay.rc:17) took 10ms and failed: finit_module for "/vendor/lib/modules/synaptics_i2c.ko" failed: Exec format error
[   35.589151] synaptics_core_module: exports duplicate symbol syna_tcm_add_module (owned by kernel)
[   35.598808] init: Command 'insmod /vendor/lib/modules/synaptics_core_module.ko' action=early-init (/vendor/etc/init/hw/init.mmi.overlay.rc:18) took 14ms and failed: finit_module for "/vendor/lib/modules/synaptics_core_module.ko" failed: Exec format error
[   35.624930] synaptics_tcm_i2c 0-004b: touch_set_input_reporting: Application firmware not running

[   35.797834] pc : device_init+0x48/0x3d8 [synaptics_device]
[   35.803296]  el0_svc+0x8/0xc
[   35.808755] lr : syna_tcm_module_work+0xc0/0x18

Change-Id: I41635e37c3cc2096bd543e3a032b0cc43faca130
Signed-off-by: zoujc <zoujc@motorola.com>
Reviewed-on: https://gerrit.mot.com/1749798
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Yang Xiao <xiaoy3@motorola.com>
Reviewed-by: Jianqi Yang <yangj@motorola.com>
Submit-Approved: Jira Key

Disable touchscreen unused config

TP:
Disable touchscreen unused config on viking

Change-Id: I915d498088e840c323be1498dd78b60a6f3c57a6
Reviewed-on: https://gerrit.mot.com/1756478
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Jichao Zou <zoujc@motorola.com>
Submit-Approved: Jira Key

Disable hypervisor UART

qcom CR :2736066

Disable hypervisor UART. Customers are capable
of selecting a different instance of UART for console
instead a standard console. In this case hypervisor
touching the UART instance which does not have clocks
enabled. This lead to NOC errors.

Change-Id: I70973a3af3a4fcf06e53f13a51a1edb40357e43d
Signed-off-by: xiaoy3 <xiaoy3@motorola.com>
Reviewed-on: https://gerrit.mot.com/1772314
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key

NFC SN110x bring up - kernel config

Add kernel config to include NFC SN110x driver to
main version

Change-Id: I96d044ffeb91dd4b59c11402d122fc687b26df94
Signed-off-by: Ningkai Zhuang <zhuangnk1@mt.com>
Reviewed-on: https://gerrit.mot.com/1753939
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Tao Sun <suntao2@motorola.com>
Submit-Approved: Jira Key

Do not use Qcom NFC driver

We move nfc driver to kernel/modules as DLKM
Not use Qcom buildin driver anymore

Change-Id: I206414b64999bb8930f17d0fe07a8b6428b050ac
Signed-off-by: Ningkai Zhuang <zhuangnk1@mt.com>
Reviewed-on: https://gerrit.mot.com/1788045
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Zishang Zhou <zhouzs1@motorola.com>
Reviewed-by: Tao Sun <suntao2@motorola.com>
Submit-Approved: Jira Key

config: support samsung's turbo write and HPB features

Samsung's HPB implementation supports chunk size range from 4K to 512K,
versus 4K only by JEDEC UFS 3.1 spec.

However Samsung HPB can only work with Samsung turbo write, not write
booster by JEDEC UFS 3.1 spec.

Change-Id: I414dda203726cbe2f35c66ab8ea10d158bb14def
Signed-off-by: yuedl1 <yuedl1@mt.com>
Reviewed-on: https://gerrit.mot.com/1818195
Reviewed-by: Qing Chang <qing@motorola.com>
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Submit-Approved: Jira Key

Dubai:therm: Disable THERMAL_STATISTICS

It cause (CR) if cooling device have many levels.
There are not any processes to use thermal statistics and it
occupy about 6.7K memory, so disable it, also see this CR.

Mot-CRs-fixed: (CR)

Change-Id: I5eba2c2b4d731ad700d1c6930f177ee9c97b18e4
Signed-off-by: zoujc <zoujc@motorola.com>
Reviewed-on: https://gerrit.mot.com/1854327
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Reviewed-by: Jianqi Yang <yangj@motorola.com>
Submit-Approved: Jira Key

config: disable CONFIG_EDAC_QCOM_LLCC_PANIC_ON_CE

Some boards are easy to see data RAM correctable error triggerred kernel
panics. As it's correctable error, Qcom suggested we can disable
CONFIG_EDAC_QCOM_LLCC_PANIC_ON_CE config

Change-Id: If1993b343598e9131084e52108a33946ec2104de
Reviewed-on: https://gerrit.mot.com/1867655
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Yinjun Chen <a7301c@motorola.com>
Submit-Approved: Jira Key

configs: disable unused touchscreen and NFC

Disable touchscreen and NFC config options
in Lahaina defconfig for Berlin and Berlna.

Change-Id: I06a0e4f5d9f5de4d8fcdd7edd0ce2f451204e385
Signed-off-by: wangxs8 <wangxs8@mt.com>
Reviewed-on: https://gerrit.mot.com/1873303
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Tested-by: Jira Key
Submit-Approved: Jira Key

config:berlna/berlin Bring up vibrator

Undefine vibrator support from Qcom, otherwise there would be two
nodes named vibrator and vibrator_1 in /sys/class/leds.

Change-Id: I5213fa0540d5f6ce92587751cbce2e79deb0b6a2
Signed-off-by: yangjq <yangjq@mt.com>
Reviewed-on: https://gerrit.mot.com/1893930
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Konstantin Makariev <kmakariev@motorola.com>
Submit-Approved: Jira Key

config: enable samsung turbo write and HPB feature

config samsung turbo write and HPB feature on sm7325. it is from samsung
 tw/HPB patch.

Change-Id: I1a5dd489b285774531f5e99b94e90658d8cd5ed7
Signed-off-by: yuedl1 <yuedl1@mt.com>
Reviewed-on: https://gerrit.mot.com/1905663
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Chuanchun Zhu <zhucc2@motorola.com>
Reviewed-by: Guobin Zhang <zhanggb@motorola.com>
Submit-Approved: Jira Key

config: enable HPB feature on skhynix ufs

enable HPB feature on skhynix ufs. this patch is from skhynix patch.
this hpb feature work on ufs2.2.

Change-Id: I59df3916ed0d54afa70bbf4e9132039375cb53a0
Signed-off-by: yuedl1 <yuedl1@mt.com>
Reviewed-on: https://gerrit.mot.com/1909631
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key

config: enable micron ufs  HPB feature on 7325

enable micron ufs HPB feature on 7325.it is well micron HPB works with
samsung HPB driver.

Change-Id: Ic8ed4920339df9722bb8564693f573eba5168698
Signed-off-by: yuedl1 <yuedl1@mt.com>
Reviewed-on: https://gerrit.mot.com/1909739
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key

config:Enable KioXia HPB driver

Enable the KioXia HPB config
to build it with QGKI

Change-Id: I60a9c212ae4231af699eb225d7cd9a3fe584ae72
Signed-off-by: a17671 <a17671@motorola.com>
Reviewed-on: https://gerrit.mot.com/2031470
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Wei Deng <dengwei1@motorola.com>
Reviewed-by: Xiangpo Zhao <zhaoxp3@motorola.com>
Submit-Approved: Jira Key

config:Enable KioXia HID driver

Enable the KioXia HID config
So 8350 will have KioXia HID driver by default

Change-Id: I01460c812ed5adca3c56ebb45498a0e3df994b75
Signed-off-by: a17671 <a17671@motorola.com>
Reviewed-on: https://gerrit.mot.com/2031474
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Wei Deng <dengwei1@motorola.com>
Reviewed-by: Xiangpo Zhao <zhaoxp3@motorola.com>
Submit-Approved: Jira Key

ufs:Enable Skhynix HID support on 7325/8350

Enable the Skhynix HID support
On 7325/8350 common platform

Change-Id: Id09e316552da99a0fa8512a129b6bfb5738c6743
Signed-off-by: a17671 <a17671@motorola.com>
Reviewed-on: https://gerrit.mot.com/2151904
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Xiangpo Zhao <zhaoxp3@motorola.com>
Submit-Approved: Jira Key

fixed ufs driver modified casues GKI boot up failed.

for IO performance, it need add HPB feature in UFS filed. and it have to
change ufs'KMI. it is failed to boot up after flash google's GKI. so just
remove HPB feature from GKI build.

Change-Id: I03c09e194dea2809ec2df11d3be2a137a21844ff
Signed-off-by: yuedl1 <yuedl1@mt.com>
Reviewed-on: https://gerrit.mot.com/1866787
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key

berlin:therm: Disabled max31760 driver.

In berlin & berlna, there are not fan device,
disabled this config item.

Change-Id: I438dd5aab91534d912a96b5a0841d9e6f67671f8
Signed-off-by: zoujc <zoujc@motorola.com>
Reviewed-on: https://gerrit.mot.com/1911692
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Jianqi Yang <yangj@motorola.com>
Submit-Approved: Jira Key

Remove unused configs

Berlin&Berlna will not support HDCP.
So remove unused configs.

Change-Id: I1a846fda20e2717b1dc552577bf360d45cf5f735
Signed-off-by: dinit 1 <liusx12@motorola.com>
Reviewed-on: https://gerrit.mot.com/1912701
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Shunde Jiang <jiangsd2@motorola.com>
Reviewed-by: Guobin Zhang <zhanggb@motorola.com>
Submit-Approved: Jira Key

configs: Disable unused touchscreen config

TP:
Disable novatek touchscreen  related config options for berlin
and berlinNa.

Change-Id: I2dcf72255761ab4c1221b991ccc8f1492858da76
Reviewed-on: https://gerrit.mot.com/1910444
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Jichao Zou <zoujc@motorola.com>
Submit-Approved: Jira Key

config:Disabled THERMAL_EMERGENCY_POWEROFF_DELAY_MS.

This case almost never happens, so disable them
on berlin&berlna.

Change-Id: I4aeec55dacce0dc980f7e546359d25bf32147fd9
Signed-off-by: zoujc <zoujc@motorola.com>
Reviewed-on: https://gerrit.mot.com/1915986
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Guobin Zhang <zhanggb@motorola.com>
Submit-Approved: Jira Key

defconfig: Add CONFIG_AF_NOISE_ELIMINATION for berlin

Add CONFIG_AF_NOISE_ELIMINATION for enable/disable actuator separate
controlling to avoid resonance noise during vibrating.

Change-Id: Id4cc5d5ee5a809ab891d5a2451c4f8108fffa938
Signed-off-by: wangshuo18 <wangshuo18@mt.com>
Reviewed-on: https://gerrit.mot.com/1928203
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Shuo Wang <wangsh18@motorola.com>
Reviewed-by: Dawei Wang <wangdw10@motorola.com>
Reviewed-by: Bolei Shang <shangbl1@mt.com>
Reviewed-by: Long Cheng <chengl1@motorola.com>
Reviewed-by: Darong Huang <huangdra@motorola.com>
Reviewed-by: Yongqin Wan <wanyq1@motorola.com>
Reviewed-by: Zhilong Wang <wangzl30@motorola.com>
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key

config: remove HPB debug config from qgki config

remove HPB debug config from qgki config. the HPB debug info write
into trace log, just remove it.

Change-Id: I562f29004fdfc9b68eb2cd0a7b5a64bd21b02e3b
Signed-off-by: yuedl1 <yuedl1@mt.com>
Reviewed-on: https://gerrit.mot.com/1934612
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key

Remove memory hotplug.

Memory hotplug harm performance when offline a granule.
It can't improve power(<1mA).
Also for disable PASR feature.

Change-Id: I314552a5683f114f63f5b8434a48bcb860aed4ca
Signed-off-by: zoujc <zoujc@motorola.com>
Reviewed-on: https://gerrit.mot.com/1942435
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key

gki:Disable CONFIG_THERMAL_STATISTICS.

LCD backlight have many levels(e.g. 2048,4096),
it will allocate large memory and failed in
cooling_device_stats_setup, cause display driver
failure.

Change-Id: Ic56b44a266c0d13470944f1551e59467c0a6688f
Signed-off-by: zoujc <zoujc@motorola.com>
Reviewed-on: https://gerrit.mot.com/1943289
Reviewed-by: Jianqi Yang <yangj@motorola.com>
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Submit-Approved: Jira Key

gki-kernel:fixed gki kernel failure

Fixed gki kernel failure,
reserve MEMORY_HOTPLUG config.

Change-Id: I1eb2dfd54b28b1056746e285f9b12db884de2b21
Signed-off-by: zoujc <zoujc@motorola.com>
Reviewed-on: https://gerrit.mot.com/1955289
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key

enable zram writeback for Berlin Family

zram writeback is used to write idle/incompressible page
to backing storage rather than keeping it in memory.
Enable it in Berlin and Berlna

Change-Id: I5907ffd7235e973ae23195ef8df9765b6efd5013
Signed-off-by: Bingqian Yang <yangbq2@motorola.com>
Reviewed-on: https://gerrit.mot.com/1916152
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Jichao Zou <zoujc@motorola.com>
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Reviewed-by: Shunde Jiang <jiangsd2@motorola.com>
Submit-Approved: Jira Key

arm64/defconfig: update dubai extra config

update dubai extra config according to new dubai OD

Change-Id: Ib4dd87ef7a83af16b7776de6b4e134dc1abcfba0
Signed-off-by: zhaoxp3 <zhaoxp3@motorola.com>
Reviewed-on: https://gerrit.mot.com/2077958
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Wang Wang <wangwang1@mt.com>
Submit-Approved: Jira Key

kernel/config: disable the CONFIG_DM_VERITY_AVB

Hardware randomly unstable will trigger "dm-verity device corrupted"
and reboot the phone. Then it will not stamp the vbmeta partition with
the "AVE0" flag, which is persistent. Then it will boot up failed at
the next boot with AVB header check failed.
Moto has own Google verified boot process with the RED alert logo.
so we ignore this.

Change-Id: I631a601e5b0f6e2f4ef06f19bb53dd29b2534c7d
Reviewed-on: https://gerrit.mot.com/2079554
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Xiaojun Ji <jixj@motorola.com>
Reviewed-by: Minghui Wei <weimh1@motorola.com>
Reviewed-by: Zhenxin Xi <xizx@motorola.com>
Submit-Approved: Jira Key
Reviewed-on: https://gerrit.mot.com/2112078

set CONFIG_HZ_300=y for Berlin

Accordingly to (CR), overall device performance has improved when
CONFIG_HZ_300 is set to y. The FPS tests results are available in URL
below:

http://perf.mot.com/apps/fps/rungraphs/?runids=44810,44788

This gerrit sets CONFIG_HZ_300 to y.

Change-Id: Iafa590c380f8206b760d7e3f7f5f69bbe2269b67
Reviewed-on: https://gerrit.mot.com/2132250
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Fernanda Schmidt <fschmidt@motorola.com>
Reviewed-by: Rafael Ortolan <rafones@motorola.com>
Reviewed-by: Carlos Pinho <cpinho@motorola.com>
Submit-Approved: Jira Key

soc: qcom: Support run queue stats build in GKI

Change QCOM_RUN_QUEUE_STATS to tristate and add exit function
to support module build for Run Queue Stats, so it can be
compiled in GKI.

Mot-CRs-fixed: (CR)

Change-Id: Ief8a96d4fc928afca6b9bf2ff26e9efa460ec4d3
Signed-off-by: Huang Yiwei <quic_hyiwei@quicinc.com>
Reviewed-on: https://gerrit.mot.com/2178189
SME-Granted: SME Approvals Granted
SLTApproved: Slta Waiver
Tested-by: Jira Key
Reviewed-by: Wang Wang <wangwang1@mt.com>
Submit-Approved: Jira Key

devconfig: enable CHACHA20 crypto configs

enable CHACHA20 Crypto support
Fix cts cases: CtsNetTestCases

Change-Id: I053406b63372ba688fe8567d0860281a9b6fb2f6
Signed-off-by: xiewen3 <xiewen3@motorola.com>
Reviewed-on: https://gerrit.mot.com/2187431
SLTApproved: Slta Waiver
SME-Granted: SME Approvals Granted
Tested-by: Jira Key
Reviewed-by: Xiangpo Zhao <zhaoxp3@motorola.com>
Submit-Approved: Jira Key